# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: index.docker.io/logrange/gravity
  tag: latest
  pullPolicy: Always

volumes:
  varlib: /var/lib
  varlog: /var/log
  extdockercontainers: /ext/docker/containers

resources: {}

podAnnotations:
  seccomp.security.alpha.kubernetes.io/pod: docker/default

nodeSelector: {}

tolerations: []

affinity: {}

