apiVersion: v1
entries:
  lr-aggregator:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-04-12T19:43:29.698978-07:00
    description: Log aggregation storage
    digest: 105efd16a6a42b1732e2a1fe06c057fab6e3868543b9a8ad1daca66a39146335
    home: https://github.com/logrange
    keywords:
    - logrange
    - logging
    - logs
    - analytics
    - aggregator
    - storage
    maintainers:
    - email: mail@logrange.io
      name: The logrange authors
    name: lr-aggregator
    urls:
    - lr-aggregator-0.1.0.tgz
    version: 0.1.0
  lr-collector:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-04-12T19:43:29.699635-07:00
    description: Log collector agent
    digest: a551aabec4a47d9989cbb00283f1c326503c3259a008e40ec9fb3a4e169fef27
    home: https://github.com/logrange
    keywords:
    - logrange
    - logging
    - logs
    - analytics
    - agent
    - collector
    maintainers:
    - email: mail@logrange.io
      name: The logrange authors
    name: lr-collector
    urls:
    - lr-collector-0.1.0.tgz
    version: 0.1.0
  lr-configs:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-04-12T19:43:29.699895-07:00
    description: K8s configs
    digest: 0dd8bc47caac7e4a8ac4b0ccb4209d409f6f94e284cc69abec9d1b744fa20132
    home: https://github.com/logrange
    keywords:
    - logrange
    - logging
    - logs
    - analytics
    - configs
    maintainers:
    - email: mail@logrange.io
      name: The logrange authors
    name: lr-configs
    urls:
    - lr-configs-0.1.0.tgz
    version: 0.1.0
  lr-forwarder:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-04-12T19:43:29.700085-07:00
    description: Log forwarding agent
    digest: a0736add42a259aa7ea54d8d255f9e19d6f44c5e1f0bf45d74cacead690b1ee0
    home: https://github.com/logrange
    keywords:
    - logrange
    - logging
    - logs
    - analytics
    - agent
    - forwarder
    maintainers:
    - email: mail@logrange.io
      name: The logrange authors
    name: lr-forwarder
    urls:
    - lr-forwarder-0.1.0.tgz
    version: 0.1.0
  lr-gravity:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-04-12T19:43:29.700917-07:00
    description: Gravity adapter
    digest: 645daecd754b5e35ed021cf4751f9f14f44a58ac7d2bcdd6283ba4a271a57a43
    home: https://github.com/logrange
    keywords:
    - logrange
    - logging
    - logs
    - analytics
    - gravity
    maintainers:
    - email: mail@logrange.io
      name: The logrange authors
    name: lr-gravity
    urls:
    - lr-gravity-0.1.0.tgz
    version: 0.1.0
generated: 2019-04-12T19:43:29.697506-07:00
