---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lr-aggregator
  namespace: kube-system
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: lr-aggregator
data:
  logrange.json: |
    {{ .Files.Get "configs/logrange.json" | nindent 4 }}
  log4g.properties: |
    {{ .Files.Get "configs/log4g.properties" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lr-collector
  namespace: kube-system
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: lr-collector
data:
  collect.json: |
    {{ .Files.Get "configs/collect.json" | nindent 4 }}
  log4g.properties: |
    {{ .Files.Get "configs/log4g.properties" | nindent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lr-forwarder
  namespace: kube-system
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: lr-forwarder
data:
  forward.json: |
    {{ .Files.Get "configs/forward.json" | nindent 4 }}
  log4g.properties: |
    {{ .Files.Get "configs/log4g.properties" | nindent 4 }}