#!/usr/bin/env bash

function check {
    code=$1;
    if [[ ${code} -ne 0 ]]; then
        echo "ERROR!"
        exit ${code}
    fi
}

################# Main #################

while [[ "$1" != "" ]]; do
    case $1 in
        -v|--version)
            shift
            VERSION=$1
            ;;
        -u|--upload)
            UPLOAD=1
            ;;
        *)
            echo "Unknown argument passed!"
            exit 1
            ;;
    esac
    shift
done

if [[ -z ${VERSION} ]]; then
    VERSION="latest"
fi

SRC_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
echo "Building docker images..."

for img_bin in "collector/lr" "forwarder/lr" "logrange/logrange"
do
    arr=(${img_bin//\// })
    img=${arr[0]}
    bin=${arr[1]}

    cd ${SRC_PATH}/${img}
    check $?

    curl -sOfL https://logrange.io/download/binaries/${VERSION}/linux/arm64/${bin} && chmod +x ${bin}
    check $?

    image=logrange/${img}:${VERSION}
    echo "Building docker image '${image}'..."
    docker build -t ${image} . >/dev/null 2>&1
    check $?

    if [[ ! -z ${UPLOAD} ]]; then
        echo "Pushing docker image '${image}'..."
        docker push ${image} >/dev/null 2>&1
        check $?
    fi

    rm -f ${SRC_PATH}/${img}/${bin}
    check $?
done

