# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

args:
  version: "v0.1.0"

image:
  repository: index.docker.io/logrange/collector
  pullPolicy: Always

volumes:
  varlog: /var/log
  varliblogrange: /var/lib/logrange
  extdockercontainers: /ext/docker/containers

resources: {}

podAnnotations:
  seccomp.security.alpha.kubernetes.io/pod: docker/default

nodeSelector: {}

tolerations: []

affinity: {}