apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "forwarder.name" . }}
  namespace: {{ .Values.args.namespace }}
  labels:
    app: {{ template "forwarder.name" . }}
    appVersion: {{ .Values.args.version }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "forwarder.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "forwarder.name" . }}
        appVersion: {{ .Values.args.version }}
        release: {{ .Release.Name }}
{{- with .Values.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.args.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config
              mountPath: /opt/logrange/lr/config
{{- range $key, $val := .Values.volumes }}
            - name: {{ $key }}
              mountPath: {{ $val }}
{{- end}}
      volumes:
        - name: config
          configMap:
            name: {{ template "forwarder.name" . }}
{{- range $key, $val := .Values.volumes }}
        - name: {{ $key }}
          hostPath:
            path: {{ $val }}
            type: DirectoryOrCreate
{{- end}}
      resources:
{{ toYaml .Values.resources | indent 8 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
