# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

args:
  version: "v0.1.1"

image:
  repository: index.docker.io/logrange/logrange
  pullPolicy: Always

service:
  annotations: {}
  type: ClusterIP
  port: 9966

volumes:
  varlog: /var/log
  varliblogrange: /var/lib/logrange
  extdockercontainers: /ext/docker/containers

resources: {}

podAnnotations:
  seccomp.security.alpha.kubernetes.io/pod: docker/default

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: logrange.io/node
              operator: Exists